- name: Ensure admin001 user exists
  user:
    name: admin001
    state: present
    shell: /bin/bash
    create_home: yes

- name: Create .ssh directory
  file:
    path: /home/admin001/.ssh
    state: directory
    owner: admin001
    group: admin001
    mode: '0700'

- name: Set authorized_keys for admin001
  copy:
    dest: /home/admin001/.ssh/authorized_keys  
    content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpuDRjWE8blRaJhTiMnERfsA+KLNAi0mv7Zf4lKCumHOXAbNmoZ4jJle9lYJuJP1/sCue27WAHD3gebm7vX3laDnJbtHgyYGtYaUS73Qhb3upjXxH+S2KOaHidClLbPB2SRQoUI7Q7rHkzvxPQjIVYEPU5XvXxekgzLat8UwaJ3cjhfnIrfFy1ab6dEsQLGbZaU/iJIUgUUXOW0JbHSeItF9oM3hMBbjB5+gjJNMK9F2CcZTQ8E+vsqU0n1AF3ld/Y80QPpSaCda1OFb3G//u4Ypc6ZQKPTLrdGXe/z9yNgnKWwNzaIRsDqPSOAblH5yULRqFrc8Xpnj2/F1JR1pvsZ9CRH8G5BO+D/r10mty4SWFusoXSlJVVLQQhaW2a9sV8fYNLbFyHQsfRFqXaRHo0xdI9rZnJNFBtBeYHwJfNFMfKt0NNTeVJgOOtg2sLsDqjyCGc7b0X3RrKiXymBVnDH9YnOb5W5N0RpFj+wjWgwyGz/WVRARbmkHqW4tjbN65IUZS8xREfV+yr6o0WgIv3egeDHbnHbQLX/qCRaQBoZF3dLzOUFErtiCeEQc8IK7WoVoKWTsfCtG4rg9vHC+hfeqQPmlBfT3oUyXpQ1wQF1q/c/+PPyjVZNCRDU7+AW2bOjFdPf1cHtykrZBHkdwBmSfsW73DlxF9RWaRCs3wukQ=="
    owner: admin001
    group: admin001
    mode: '0600'

- name: Allow admin001 to use sudo without password
  copy:
    dest: /etc/sudoers.d/admin001
    content: "admin001 ALL=(ALL) NOPASSWD: ALL\n"
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'
  become: yes
