---
- name: Configure backend servers
  hosts: backends
  become: yes
  roles:
    - backend

- name: Configure HAProxy servers
  hosts: haproxy
  become: yes
  gather_facts: yes
  vars:
    keepalived_interface: eth0
  roles:
    - haproxy
